name: grg
channels:
  - pyviz
  - conda-forge
  - https://repo.anaconda.com/pkgs/main/osx-arm64/
  - defaults
dependencies:
  - cartopy=0.21.0
  - gsw=3.6.16
  - hvplot=0.8.2
  - matplotlib=3.6.2
  - numpy=1.23.4
  - pandas=1.4.4
  - xarray=2022.11.0
  - cmocean==2.0
  - statsmodels=0.13.5
  - h5netcdf=1.0.2   
  - libnetcdf=4.8.1
  - netcdf4=1.6.1
